### ISSUE TITLE
Add licensing

### ISSUE THREAD

**Issue by gakz** [hashgraph/did-sdk-js#2]
### Description

There is no licensing included in this project; I presume it would follow Hedera's standard with an Apache 2.0 – 

Licensed under Apache License, Version 2.0 – see LICENSE in this repo or apache.org/licenses/LICENSE-2.0.

### Steps to reproduce

N/A

### Additional context

<img width="890" alt="image" src="https://user-images.githubusercontent.com/5248425/128087743-2b3f1297-98ac-4bf1-b3cb-cb81d8ead979.png">

### Hedera network

other

### Version

0

**Comment by danielnorkin** [comment]
adding @rbair23 for visibility to this issue.
